repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v2.2.3
    hooks:
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: flake8
        args: ["--ignore=W504,E501"]
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.7.0
    hooks:
    -   id: autopep8
        args: [--ignore=E501, --in-place]
-   repo: https://github.com/asottile/reorder_python_imports.git
    rev: v1.9.0
    hooks:
    -   id: reorder-python-imports
        files: .*\.py$
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        args: ['--py37-plus']
